### ISSUE TITLE
It's possible use column FILTER and DATA ORDER by column?

### ISSUE THREAD

**Issue by APMU** [farseerdev/sheet-happens#4]
Hello,

SHEET-HAPPENS it's a nice project!

But, it is possible use/add column FILTER and DATA ORDER by column feature?

**Comment by APMU** [comment]
Hi @Luka-M !

It's possible add this feature? (FILTER and COLUMN ORDER)

Thanks.

**Comment by APMU** [comment]
?

**Comment by Luka-M** [comment]
@APMU This component only renders the spreadsheet - the data processing (including filter and sort) should be handled outside of it.
